- name: insure than apache is not running
  package: name=apache2 enabled=false state=stopped

- name: Install nginx
  package: name=nginx state=present

- name: Install uwsgi
  package: name=uwsgi state=present

- name: Install fastcgi for php support
  package: name=php-fpm state=present

- name: put the config file in place
  template: src={{ item.src}}  dest={{ item.dest }}
  with_items:
     - { src: "kalite-nginx.conf",dest: "/etc/nginx/sites-available/" }
     - { src: "kiwix-nginx.conf",dest: "/etc/nginx/sites-available/" }
     - { src: "server.conf",dest: "/etc/nginx/" }
     - { src: "nginx.conf",dest: "/etc/nginx/" }

- name: remove the nginx default config
  file: src=/etc/nginx/sites-available/default state=absent

- name: create the links 
  file: src=/etc/nginx/sites-available/kalite_nginx.conf
        dest=/etc/nginx/sites-enabled/kalite_nginx.conf
        state=link

- name: link enable kiwix
  file: src=/etc/nginx/sites-available/kiwix_nginx.conf
        dest=/etc/nginx/sites-enabled/kiwix_nginx.conf
        state=link
