- name: Install nginx
  package: name=nginx state=present

- name: Install nginx
  package: name=uwsgi state=present

- name: put the config file in place
  template: src=nginx.conf dest=/etc/nginx/sites-enabled/
