---
# The values here are default local variables.
gui_wan_iface: "unset"
gui_static_wan_ip: "unset"
gui_desired_network_role: Gateway
wondershaper_dspeed: "4096"
wondershaper_upspeed: "1024"
# WiFi
host_ssid: IIAB
hostapd_wait: 10
host_wifi_mode: g
host_channel: 6
host_wireless_n: False
host_country_code: US
hostapd_secure: True
hostapd_password: "iiab2017"
driver_name: nl80211
network_config_dir: /etc/network/interfaces.d
iiab_network_mode: "Gateway"
dns_jail_enabled: False
services_externally_visible: False

# following variables set for old apache,dhcpd,named usage
#  Note: computed services makes decision on what to enable 
#       So do not install both dhcpd and dnsmasq
dhcpd_install: False
dhcpd_enabled: False
named_install: False
named_enabled: False
dnsmasq_install: True
dnsmasq_enabled: True
nginx_install: True
nginx_enabled: True
captive_portal_enabled: False
dansguardian_install: False
dansquardian_enabled: False
squid_install: False
squid_enabled: False
