openvpn_install: True
openvpn_enable: False

# For /etc/iiab/openvpn_handle
openvpn_handle: ""

# cron seems necessary on CentOS:
openvpn_cron_enabled: False

openvpn_server: xscenet.net
openvpn_server_virtual_ip: 10.8.0.1
openvpn_server_port: 1194
