- name: Get python dateutil
  package:
     name: python-dateutil
     state: present
  when: py_captive_portal_install
  
- name: Create directory for Captive Portal script
  file:
    path: /opt/iiab/captive-portal
    state: directory
  when: py_captive_portal_install

- name: Copy Captive Portal script
  template:
    src: roles/network/templates/captive_portal/capture_wsgi.py.j2
    dest: /opt/iiab/captive-portal/capture_wsgi.py
    owner: root
    group: root
    mode: 0740
  when: py_captive_portal_install

- name: Copy Captive Portal service file
  template:
    src: roles/network/templates/captive_portal/captive_portal.service.j2
    dest: /etc/systemd/system/captive_portal.service
    owner: root
    group: root
    mode: 0644
  when: py_captive_portal_install

- name: Copy Captive Portal Apache config file
  template:
    src: roles/network/templates/captive_portal/001-captive_portal.conf.j2
    dest: /etc/{{ apache_config_dir }}/001-captive_portal.conf
    owner: root
    group: root
    mode: 0740
  when: py_captive_portal_install and py_captive_portal_enabled

- name: Enable captive_portal after copying files
  service:
    name: captive_portal.service
    enabled: yes
  when: py_captive_portal_install and py_captive_portal_enabled

- name: Enable Apache config file
  file:
    src: /etc/apache2/sites-available/001-captive_portal.conf
    dest: /etc/apache2/sites-enabled/001-captive_portal.conf
    state: link
  when: py_captive_portal_enabled and is_debuntu

- name: Start captive_portal after copying files
  service:
    name: captive_portal.service
    state: started
  when: py_captive_portal_install and py_captive_portal_enabled

- name: Disable captive_portal after copying files
  service:
    name: captive_portal.service
    enabled: no
  when: py_captive_portal_install and not py_captive_portal_enabled

- name: Stop captive_portal after copying files
  service:
    name: captive_portal.service
    state: stopped
  when: py_captive_portal_install and not py_captive_portal_enabled

- name: Disable Apache config file
  file:
    dest: /etc/apache2/sites-enabled/001-captive_portal.conf
    state: absent
  when: not py_captive_portal_enabled and is_debuntu
