- name: No LAN configured - Appliance mode
  set_fact:
    dansguardian_enabled: False
    squid_enabled: False
    dhcpd_enabled: False
    wondershaper_enabled: False
    iiab_network_mode: "Appliance"
  when: iiab_lan_iface == "none" or user_lan_iface == "none"

- name: LAN configured - LanController mode
  set_fact:
    dansguardian_enabled: False
    squid_enabled: False
    wondershaper_enabled: False
    iiab_network_mode: "LanController"
  when: iiab_lan_iface != "" and iiab_wan_iface == "none"

- name: LAN configured - Gateway mode
  set_fact:
    iiab_network_mode: "Gateway"
  when: 'iiab_lan_iface != "none" and iiab_wan_iface != "none"'

- name: enable dhcpd if appropriate
  set_fact:
    dhcpd_enabled: True
  when: iiab_lan_iface != "" and iiab_lan_iface != "none"  and dhcpd_install

- name: enable nginx if appropriate
  set_fact:
    nginx_enabled: True
  when: iiab_lan_iface != "" and iiab_lan_iface != "none"  and nginx_install

- name: Add location section to config file
  ini_file: dest='{{ iiab_config_file }}'
            section=network
            option='{{ item.option }}'
            value='{{ item.value }}'
  with_items:
  - option: 'iiab_network_mode_applied'
    value: '{{ iiab_network_mode }}'
