- name: Install dhcp package
  package: name=isc-dhcp-server
           state=present
  when: is_debuntu and dhcpd_install

# if this is an upgrade - may need to disable already present package
- name: Disable dhcpd
  package: name=isc-dhcp-server enabled=False state=stopped
  when: is_debuntu and not dhcpd_enabled
  ignore_errors: True

- name: Install dhcp package
  package: name=dhcp
           state=present
  when: is_redhat and dhcpd_install

# if this is an upgrade - may need to disable already present package
- name: Disable dhcp
  package: name=dhcp enabled=False state=stopped
  when: is_redhat and not dhcpd_enabled
  ignore_errors: True

- name: Create non-privileged user
  user: name=dhcpd
        createhome=no

- name: Configure dhcpd
  template: src={{ item.src }}
            dest={{ item.dest }}
            owner=root
            group=root
            mode={{ item.mode }}
  with_items:
   - { src: 'dhcp/dhcpd-iiab.conf.j2', dest: '/etc/dhcpd-iiab.conf', mode: '0644' }
   - { src: 'dhcp/dhcpd.service', dest: '/etc/systemd/system/dhcpd.service', mode: '0755' }

- name: Create dhcpd needed files
  command: touch /var/lib/dhcpd/dhcpd.leases
           creates=/var/lib/dhcpd/dhcpd.leases
  when: is_redhat

- name: Check leases permissions
  file: path=/var/lib/dhcpd/dhcpd.leases
        owner=dhcpd
        group=dhcpd
        mode=0644
        state=file
  when: is_redhat
