- include: computed_network.yml
  when: not installing
  tags:
    - network
    - network-discover

- name: Set hostname
  template: dest=/etc/hostname
            src=network/hostname.j2
            owner=root
            mode=0644
  tags:
    - network
    - domain

- name: Configure /etc/sysconfig/network
  template: src=network/sysconfig.network.j2
            dest=/etc/sysconfig/network
            owner=root
            group=root
            mode=0644
  tags:
    - network
    - domain

- name: Create iiab_domain_name flag
  template: src=network/{{ item }}.j2
            dest=/etc/sysconfig/{{ item }}
            mode=0644
  with_items:
    - iiab_domain_name
  register: domainname
  tags:
    - network
    - domain


##### Start static ip address info for first run #####
#- include: static.yml
#  when: 'iiab_wan_iface != "none" and wan_ip != "dhcp"'
##### End static ip address info

- include: hosts.yml

- include: named.yml
 
- include: dhcpd.yml

- include: dnsmasq.yml
  when: dnsmasq_enabled

- include: squid.yml

- include: wondershaper.yml

- include: iptables.yml

- include: avahi.yml

- name: ask systemd to reread the unit files, picks up changes done
  shell: systemctl daemon-reload
  when: not installing

- include: ifcfg_mods.yml
  when: is_redhat and not installing

- include: debian.yml
  when: is_debuntu and not is_rpi  and not installing

- include: rpi_debian.yml
  when: is_debuntu and is_rpi  and not installing

- name: Create iiab network flags
  template: src=network/{{ item }}.j2
            dest=/etc/sysconfig/{{ item }}
            mode=0644
  with_items:
    - iiab_wan_device
    - iiab_lan_device
  when: not installing

- include: computed_services.yml
 
- include: enable_services.yml

- include: restart.yml
  when: not installing

- include: hostapd.yml
  when: not installing
