- name: Copy template script to /usr/libexec/iiab-startup.sh
  template:
    src: iiab-startup.sh
    dest: /usr/libexec/
    mode: 0755

- name: Copy iiab-startup.service to {{ systemd_location }}
  template:
    src: iiab-startup.service
    dest: "{{ systemd_location }}"

- name: Enable & restart the systemd service after daemon-reload
  systemd:
    name: iiab-startup
    daemon_reload: yes
    enabled: yes
    state: restarted
