- name: Disable systemd-networkd.service
  service: name=systemd-networkd.service
           enabled=no
  when: not is_centos

- name: Mask systemd-networkd.service
  shell: 'systemctl mask systemd-networkd'
  when: not is_centos

- name: Disable systemd-hostnamed.service
  service: name=systemd-hostnamed.service
           enabled=no

- name: Disable dbus-org.freedesktop.hostname1.service
  service: name=dbus-org.freedesktop.hostname1
           enabled=no

- name: Mask dbus-org.freedesktop.hostname1.service
  shell: 'systemctl mask dbus-org.freedesktop.hostname1'

- name: Disable network.service
  service: name=network
           enabled=no

- name: Mask network.service
  shell: 'systemctl mask network.service'

# Network Manager starts this if needed
- name: Disable wpa_supplicant
  service: name=wpa_supplicant
           enabled=no

- name:  Does systemd-udevd.service exist
  stat: "{{ systemd_location }}/systemd-udevd.service"
  register: udev_unit

- name: Copy udevd service to /etc/systemd/system to modify
  copy: src={{ systemd_location }}/systemd-udevd.service
        dest=/etc/systemd/system/systemd-udevd.service
        owner=root
        group=root
        mode=0644
  when: udev_unit.stat.exists is defined and udev_unit stat.exists

- name: Change MountFlags from slave to shared
  lineinfile: backup=no
              dest=/etc/systemd/system/systemd-udevd.service
              regexp='^MountFlags'
              line='MountFlags=shared'
              state=present
  when: udev_unit.stat.exists is defined and udev_unit stat.exists

- name: Ask systemd to recognize the changes
  systemd: name=systemd-udevd 
           daemon-reload=True
           state=restarted
  when: udev_unit.stat.exists is defined and udev_unit stat.exists

