- name: Make sure the required directorie exist
  file:
      path: '{{ magrit_venv }}'
      state: directory

- name: Install packages reqpured for magrit thematic mapping https://github.com/riatelab/magrit
  package:
    name:
      - libpython3.5-dev 
      - python3.5 
      - python3.5-dev 
      - python3-pip
      - libopenblas-dev 
      - libopenblas-base 
      - libfreetype6-dev 
      - libfreetype6 
      - libproj-dev
      - libspatialindex-dev 
      - libv8-3.14-dev 
      - libffi-dev 
      - node-gyp
      - libuv1-dev
      - libxslt1-dev 
      - libxml2 
      - libxml2-dev 
      - libkml-dev 
      - libgeos-dev
      - redis-server 
      - libatlas-base-dev
    state: present
  when: internet_available and is_rpi
  tags:
    - download

- name: Install packages reqpured for magrit thematic mapping https://github.com/riatelab/magrit -- other than rpi
  package:
    name:
      - libpython3.5-dev 
      - python3.5 
      - python3.5-dev 
      - python3-pip
      - libopenblas-dev 
      - libopenblas-base 
      - libfreetype6-dev 
      - libfreetype6 
      - libproj-dev
      - libspatialindex-dev 
      - libv8-3.14-dev 
      - libffi-dev 
      - node-gyp
      - libuv1-dev
      - libxslt1-dev 
      - libxml2 
      - libxml2-dev 
      - libkml-dev 
      - libgeos-dev
      - redis-server 
      - libatlas-base-dev
      - gdal-bin
      - libgdal-dev
      - libgdal1-dev
      - libgdal1i
      - libgdal-doc
      - python3-ujson
      - python3-gdal
    state: present
  when: internet_available and not is_rpi
  tags:
    - download
- name: Check if our package is already downloaded
  stat: 
      path: '{{ downloads_dir }}/gdal_2.2.3-1_armhf.deb'
  register: p

- name: Download our compiled version of Geospatial Data Abstraction lIbrary (GDAL)
  get_url:
    url: '{{ iiab_download_url }}/gdal_2.2.3-1_armhf.deb'
    dest: '{{ downloads_dir }}'
  when: p.stat.isdir is defined and p.stat.isdir and  internet_available and is_rpi

- name: Install GDAL
  shell: "apt-get install {{ downloads_dir }}/gdal_2.2.3-1_armhf.deb"
  args:
     warn: false
  when: internet_available and is_rpi
      
- name: Clone magrit repo
  git:
    repo: https://github.com/riatelab/magrit
    dest: "{{ magrit_venv }}"
    version: master
    update: yes
    force: yes
  when: internet_available and magrit_install

- name: Install magrit with dependencies using pip, into virtualenv (debuntu)
  pip:
    name: 
      - numpy
      - ujson
      - docopt
      - pandas 
    virtualenv: "{{ magrit_dir }}"
    virtualenv_python: python3.7
  when: internet_available

- name: Install the magrit requirements
  pip:
    requirements: '{{ magrit_venv }}/requirements/dev.txt'
    virtualenv: "{{ magrit_dir }}"
    virtualenv_python: python3.7

- name: Edit the python environment spec
  lineinfile:
      path: '{{ magrit_venv }}/magrit_app/app.py'
      regexp: '^#!/usr/bin/env.*'
      line: '#!/usr/bin/env python3.7'

- name: Put systemd service file
  template:
      src: magrit.service.j2
      dest: /etc/systemd/system/magrit.service

- name: Enable systemd for magrit
  systemd:
      enabled: True
      started: True
  when:
      magrit_enabled: True

- name: Disable systemd for magrit
  systemd:
      enabled: False
      started: False
  when:
      magrit_enabled == False
