- name: Create home directory
  file: path={{ doc_root }}/home
        mode=0755
        owner={{ apache_user }}
        group={{ apache_user }}
        state=directory

- name: Install admin home page into nginx
  template: src=iiab-home-page.conf
            dest=/etc/{{ apache_config_dir }}/
  when: not nginx_enabled

