- name: Create home directory
  file: path={{ doc_root }}/home
        mode=0755
        owner={{ apache_user }}
        group={{ apache_user }}
        state=directory

- name: Install admin home page into apache2
  template: src=iiab-home-page.conf
             dest=/etc/{{ nginx_config_dir }}/iiab-home-page.conf

- name: Enable the home page
  file: src=/etc/{{ nginx_config_dir }}/iiab-home-page.conf
        dest=/etc/nginx/sites-enabled/iiab-home-page.conf
        state=link
  when: is_debuntu
