- name: Create home directory
  file: path={{ doc_root }}/home
        mode=0755
        owner={{ apache_user }}
        group={{ apache_user }}
        state=directory

- name: Install admin home page into apache2
  template: src=xsce-home-page.conf
             dest=/etc/{{ apache_config_dir }}/xsce-home-page.conf

- name: Enable the home page
  file: src=/etc/{{ apache_config_dir }}/xsce-home-page.conf
        dest=/etc/apache2/sites-enabled/xsce-home-page.conf
        state=link
  when: is_debuntu
