# Setup specific to the Raspberry Pi
#
#
- name: Check for needing to enable i2c rtc device in config.txt
  lineinfile: dest=/boot/config.txt
              line="dtoverlay=i2c-rtc,{{ rtc_id }}=on"
              state=present

- name: Add the usbnet driver
  lineinfile: dest=/boot/config.txt
              line="dtoverlay=dwc2,g_ether"
              state=present
  when: usbnet_install

- name: Load the modules at boot time
  shell: sed -i -e 's/yes rootwait/yes load-modules=dwc2,g_ether net.ifnames=0 rootwait/' /boot/cmdline.txt
  when: usbnet_install
 
- name: disable the loading of modules at boot time
  shell: sed -i -e 's/yes load-modules=dwc2,g_ether net.ifnames=0 rootwait/yes rootwait/' /boot/cmdline.txt
  when: not usbnet_install
 
- name: Add a udev rule to transfer hwclock to system clock at dev creation
  template: src=item.src
            dest=item.dest
            owner=root
            group=root
            mode=0644
  with_items:
     - { src: "92-rtc-i2c.rules", dest: "/etc/udev/rules.d/92-rt-i2c.rules" }

- name: pre-Install packages
  package: name={{ item }}
           state=latest
  with_items:
    - ntp

- name: increase the swap file size (kalite pip download fails)
  lineinfile: regexp="^CONF_SWAPSIZE"
              line=CONF_SWAPSIZE=500
              dest=/etc/dphys-swapfile

- name: restart the swqp service
  command: /etc/init.d/dphys-swapfile restart

- name: Add rpi rootfs resizing service
  template: src={{ item.src }}
            dest={{ item.dest }}
            owner=root
            group=root
            mode={{ item.mode }}
  with_items:
    - { src: 'iiab-rpi-max-rootfs.sh', dest: '/usr/sbin/iiab-rpi-max-rootfs.sh', mode: '0755'}
    - { src: 'iiab-rpi-root-resize.service', dest: '/etc/systemd/system/iiab-rpi-root-resize.service', mode: '0644'}

- name: Enable rootfs resizing service
  service: name=iiab-rpi-root-resize
           enabled=yes
